### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by Tenome** [andyroodee/ADPCM#1]
Would you mind giving an example of how to use this? I compiled it from the source, but I can't make the command prompt parameters work. Thanks.

**Comment by BalloonPark** [comment]
I put the .p04 files in the same directory as the executable, open a command window in that folder, and finally I enter the below:

`C:\ADPCM\bin\Debug>adpcm.exe 351S.P04 22000 .p04 C:\`

`usage: ADPCM.exe source [frequency] [sourceFileExtension] [destination]`

adpcm.exe is the complied executable 
351S.P04 = source; the sound file you want to convert, this is a sample file name from the disk.
22000 = frequency; This will effect the pitch / speed. I'm not sure how it works or what would be correct, 20000-22000 sounds close to in game.
C:\ = destination; Folder you want the converted .wav files to show up.

Hope this helps!
